addons:
  chrome: stable
  firefox: latest
language: python
python:
  - 2.7
  - 3.6
stages:
  - test
  - name: deploy
    if: tag IS true
env:
  - BROWSER=chrome
  - BROWSER=firefox
jobs:
  include:
    - stage: deploy
      addons:
      python: 3.6
      env:
      before_install:
      after_success:
      install: pip install -U setuptools setuptools_scm
      script: skip
      deploy:
        provider: pypi
        user: misharov
        distributions: sdist bdist_wheel
        skip_upload_docs: true
        password:
          secure: MgMJyPSiI77b+zmeTKPLl/NP5JBo7JyIZfA3mJEqd0+39sAp5QWMGGctJ0FWq3/QL12feurVsHtlLtdFPma+yGCGus6+5HFHAHlRJTg7tJAvDwbWhXmVtKAA49BaxQdhSBh8Wa+ff9T+wBrq7xjxLNlig/RPTlAqw0pXkl20rVSYhKgZpOmSbeyGuSiyhrYjnVfnsfCchBSOrx/tEj1/sH/3ib+FX992eqOuOTY+rtSS3jSITaGelDdW4L1L2x/CT/mzTczUeqYMTQ170YHmd8pr+3PkV1LX81vXqZn9kfAR2dszlCgB9fWFJ/NnLfYBe4sWcWydm6l25NucX4JB9Y3Aoi6PlvCLROFXjlW9d3KIGDKnc6yLDehpSryQnxKbJnhvGlVbjxxfrjEzECICXIUn2/1+zNBoUTSQ7QjLnNhRwZ2lOjWqMfzkjswzzWh8j21Qq6WDK9XTpjBZqbl2jQfAo5NvnYSvf0xmSQs6ZC/+am7CjmEgugpdqB5f7QX+5AD6pBIMqUs9Zs9qGlBTZ2g/YFjApewfCWjXv1yelnJiisrP1IFGM8nVNDurg6f+wQ+QKry9KTiXTTxq2FEuY+vBFUrH26+tBmFl1YJnkWoDSCN6vPvADg1FUmbTOosCRAAaqjjX5VK1RknigROqDP2boOKBhnx/QxTStiwpLkI=
        on:
          tags: true
before_install:
  - pip install -U setuptools pip
  - pip install flake8 pytest webdrivermanager
  - webdrivermanager $BROWSER
install: python setup.py install
script:
  - flake8 src testing --max-line-length=100
  - py.test -v
