addons:
  chrome: stable
  firefox: latest
language: python
python:
  - 2.7
  - 3.6
stages:
  - test
  - name: deploy
    if: tag IS true
env:
  - BROWSER=chrome
  - BROWSER=firefox
jobs:
  include:
    - stage: deploy
      addons:
      python: 3.6
      env:
      before_install:
      after_success:
      install: pip install -U setuptools setuptools_scm
      script: skip
      deploy:
        provider: pypi
        user: misharov
        distributions: sdist bdist_wheel
        skip_upload_docs: true
        password:
          secure: aZkbUdd5GFnhH8US+yl8gvhlIxlQ/DqePan6ZPQeuvVUAZACfthseaWlpbWOabA8OP37gncoOhy4ygz1A9lq+RZPu6V+7FPGcq/uzP2Qe4mYE0wgq7j7ssmbniP8fqydWBgPAd5TIIIonIWIUw5YQ3nu2DjPww99U0xWL2SK6vT+hBr30P/oowBZvoR6xtgEP98WMOiG4+8UrYSSFrNU1P4onaiOrztN1Iur3S8TsqsTnwbphKmJ4a3QDzXYpUXDzrNRbmB/v5YNmW+uca/8JQvuyfNbNWzqf0tC2vnTgAWs4NqBlo3byQDsEd2ZaCrP/dKZvgTidey/geHu0ZO5Lt8apJ4FTUZjyUAVWdZ5JMN76ncSexEbhGeVq2r4tg+UCSuc+UQ84lynOd9mp9b1fS6zd92c2wLR22FBZcQM2VlpKWNTrsAVK/5CeZTJguk/V9oTSWvo570llQTUrQqU3bc2wXwr2rHsZ1OiYdxG+BGPMRQmb9eXNUGNOg25iTfGMRC9lNb5gSr/9J1F2ENcX6dwCa8aDbniLQMITof0s4f3f0VmeGev95QBOfMVC6NP4Y51cfmw61WP9tx9LpyqCVJrFmUc1QxFoHuxzkL23DJ6nykRRuvob8uMt3Cxmj/1axp26XVdhVuWTe1jKQbopDqFM70In3RBKpCTIAlEpiQ=
        on:
          tags: true
before_install:
  - pip install -U setuptools pip
  - pip install flake8 pytest pytest-cov coveralls
  - pip install git+https://github.com/quarckster/webdriverdownloader.git@geckodriver_fix
  - webdriverdownloader $BROWSER
install: python setup.py install
script:
  - flake8 src testing --max-line-length=100
  - py.test -v --cov widgetastic_patternfly4 --cov-report term-missing
after_success: coveralls
